# Generated by Django 3.2 on 2021-04-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_pimage_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categorys',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategorys',
        ),
    ]
