# Generated by Django 3.2 on 2021-05-09 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210429_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='images',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.pimage'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='images',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.pimage'),
        ),
    ]
