# Generated by Django 3.2 on 2021-05-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210509_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'color'},
        ),
        migrations.AlterModelOptions(
            name='offermodel',
            options={'managed': True, 'verbose_name': 'Offer'},
        ),
        migrations.AlterModelOptions(
            name='sizemodel',
            options={'verbose_name': 'Size'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, to='products.ColorModel'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='offers',
        ),
        migrations.AddField(
            model_name='product',
            name='offers',
            field=models.ManyToManyField(blank=True, null=True, to='products.OfferModel'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='products.SizeModel'),
        ),
    ]
