# Generated by Django 3.2 on 2021-05-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210509_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='images',
        ),
        migrations.AddField(
            model_name='brand',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, to='products.PImage'),
        ),
    ]
